# Generated by Django 5.1.3 on 2024-11-14 02:37

import django.db.models.deletion
import django.utils.timezone
import django_enum.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100)),
                ('quantity', models.IntegerField(default=1)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
                ('staff_capacity', models.IntegerField()),
                ('fire_engine_capacity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Dispatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incident', django_enum.fields.EnumPositiveSmallIntegerField(choices=[(1, 'Structure Fire'), (2, 'Wild Fire'), (3, 'Vehicle Fire'), (4, 'Hazmat Fire'), (5, 'Medical Emergency'), (6, 'Vehicle Accident'), (7, 'Water Rescue'), (8, 'Hazmat Accident'), (9, 'Natural Disaster'), (10, 'Technical Rescue')])),
                ('reported_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('notified_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('address', models.CharField(max_length=250)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('incident__in', [1, 2, 3, 4, 5, 6, 7, 8, 9, 10])), name='fire_station_Dispatch_incident_IncidentType')],
            },
        ),
        migrations.CreateModel(
            name='FireEngine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engine_number', models.IntegerField()),
                ('model', models.CharField(max_length=100)),
                ('license_plate', models.CharField(max_length=10)),
                ('equipments', models.ManyToManyField(to='fire_station.equipment')),
            ],
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift_start', models.TimeField()),
                ('shift_end', models.TimeField()),
                ('day', django_enum.fields.EnumPositiveSmallIntegerField(choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday'), (7, 'Sunday ')])),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('day__in', [1, 2, 3, 4, 5, 6, 7])), name='fire_station_Shift_day_DayOfWeek')],
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('gender', django_enum.fields.EnumCharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=6)),
                ('position', models.CharField(max_length=100)),
                ('shift', models.ManyToManyField(to='fire_station.shift')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fire_station.station')),
            ],
        ),
        migrations.CreateModel(
            name='FireFighter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', django_enum.fields.EnumPositiveSmallIntegerField(choices=[(1, 'FireFighter'), (2, 'Engineer'), (3, 'Lieutenant'), (4, 'Captain'), (5, 'District Chief'), (6, 'Division Chief'), (7, 'Deputy Fire Chief'), (8, 'Fire Chief')])),
                ('role', django_enum.fields.EnumCharField(choices=[('Incident Commander', 'Incident Commander'), ('Company Officer', 'Company Officer'), ('Hoseline Operator', 'Hoseline Operator'), ('Nozzle Operator', 'Nozzle Operator'), ('Vent Technician', 'Vent Technician'), ('Search and Rescue', 'Search and Rescue Technician'), ('Medic', 'Medical Technician')], max_length=18)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fire_station.staff')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('rank__in', [1, 2, 3, 4, 5, 6, 7, 8])), name='fire_station_FireFighter_rank_FireFighterRank'), models.CheckConstraint(condition=models.Q(('role__in', ['Incident Commander', 'Company Officer', 'Hoseline Operator', 'Nozzle Operator', 'Vent Technician', 'Search and Rescue', 'Medic'])), name='fire_station_FireFighter_role_FireFighterRole')],
            },
        ),
        migrations.AddConstraint(
            model_name='staff',
            constraint=models.CheckConstraint(condition=models.Q(('gender__in', ['Male', 'Female', 'Other'])), name='fire_station_Staff_gender_Gender'),
        ),
    ]
