# Generated by Django 5.1.1 on 2024-11-16 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fire_station', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='station_name',
            field=models.CharField(default='Station Alpha', max_length=255),
            preserve_default=False,
        ),
    ]
