# Generated by Django 5.1.1 on 2024-11-16 08:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fire_station', '0002_station_station_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispatch',
            name='equipment_used',
            field=models.ManyToManyField(to='fire_station.equipment'),
        ),
        migrations.AddField(
            model_name='dispatch',
            name='fire_engine',
            field=models.ManyToManyField(to='fire_station.fireengine'),
        ),
        migrations.AddField(
            model_name='dispatch',
            name='fire_fighter',
            field=models.ManyToManyField(to='fire_station.firefighter'),
        ),
        migrations.AddField(
            model_name='dispatch',
            name='resolved_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dispatch',
            name='station',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='fire_station.station'),
            preserve_default=False,
        ),
    ]
