# Generated by Django 5.1.1 on 2024-11-16 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fire_station', '0003_dispatch_equipment_used_dispatch_fire_engine_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment',
            name='quantity',
        ),
    ]
