# Generated by Django 5.1.3 on 2024-11-16 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fire_station', '0004_remove_equipment_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipment',
            old_name='date',
            new_name='issue_date',
        ),
    ]
