# Generated by Django 5.1.3 on 2024-11-20 07:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fire_station', '0005_rename_date_equipment_issue_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firefighter',
            name='staff',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='fire_station.staff'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='shift',
            field=models.ManyToManyField(blank=True, to='fire_station.shift'),
        ),
    ]
