# Generated by Django 5.1.3 on 2024-11-24 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fire_station', '0006_fireengine_station'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fireengine',
            name='equipments',
            field=models.ManyToManyField(blank=True, to='fire_station.equipment'),
        ),
    ]
