# Generated by Django 5.1.3 on 2024-11-29 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fire_station', '0006_alter_firefighter_staff_alter_staff_shift'),
        ('fire_station', '0007_alter_fireengine_equipments'),
    ]

    operations = [
    ]
